//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZakazivanjePregledaEntities : DbContext
    {
        public ZakazivanjePregledaEntities()
            : base("name=ZakazivanjePregledaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblDoktor> tblDoktors { get; set; }
        public virtual DbSet<tblKorisnik> tblKorisniks { get; set; }
        public virtual DbSet<tblPacijent> tblPacijents { get; set; }
        public virtual DbSet<tblPodtipPregleda> tblPodtipPregledas { get; set; }
        public virtual DbSet<tblPregled> tblPregleds { get; set; }
        public virtual DbSet<tblTipPregleda> tblTipPregledas { get; set; }
        public virtual DbSet<tblUstanova> tblUstanovas { get; set; }
        public virtual DbSet<tblVrstaPregleda> tblVrstaPregledas { get; set; }
        public virtual DbSet<vwDoktor> vwDoktors { get; set; }
        public virtual DbSet<vwPacijent> vwPacijents { get; set; }
        public virtual DbSet<vwPodtipPregleda> vwPodtipPregledas { get; set; }
        public virtual DbSet<vwTipPregleda> vwTipPregledas { get; set; }
        public virtual DbSet<vwUstanova> vwUstanovas { get; set; }
        public virtual DbSet<vwVrstaPregleda> vwVrstaPregledas { get; set; }
        public virtual DbSet<vwPregled> vwPregleds { get; set; }
    }
}
