//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDoktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoktor()
        {
            this.tblPregleds = new HashSet<tblPregled>();
        }
    
        public int doktorID { get; set; }
        [System.ComponentModel.DisplayName("Ime")]
        public string imeDoktora { get; set; }
        [System.ComponentModel.DisplayName("Prezime")]
        public string prezimeDoktora { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [System.ComponentModel.DisplayName("Datum rodjenja")]
        public Nullable<System.DateTime> datumRodjenjaDoktora { get; set; }
        [System.ComponentModel.DisplayName("Broj telefona")]
        public string brojTelefonaDoktora { get; set; }
        [System.ComponentModel.DisplayName("Broj licence")]
        public string brojLicence { get; set; }

        [System.ComponentModel.DisplayName("Specijalizacija")]
        public string specijalizacija { get; set; }
        [System.ComponentModel.DisplayName("Doktor")]
        public string doktor
        {
            get {
                return imeDoktora + " " + prezimeDoktora;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPregled> tblPregleds { get; set; }
    }
}
