//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKorisnik
    {
        public int korisnikID { get; set; }

        [System.ComponentModel.DisplayName("Sifra")]
        public string sifraKorisnika { get; set; }

        [System.ComponentModel.DisplayName("Email")]
        public string emailKorisnika { get; set; }

        [System.ComponentModel.DisplayName("Potvrdi sifru")]
        public string potvrdjenaSifraKorisnika { get; set; }
    }
}
