//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPregled
    {
        public int pregledID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [System.ComponentModel.DisplayName("Datum")]
        public Nullable<System.DateTime> terminPregleda { get; set; }

        [Required(ErrorMessage = "Appointment Time is required")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}")]

        [System.ComponentModel.DisplayName("Vreme")]
        public Nullable<System.TimeSpan> vremePregleda { get; set; }

        [System.ComponentModel.DisplayName("Dodatne napomene")]
        public string dodatneNapomene { get; set; }

        [System.ComponentModel.DisplayName("Ustanova")]
        public Nullable<int> ustanovaID { get; set; }

        [System.ComponentModel.DisplayName("Pacijent")]
        public Nullable<int> pacijentID { get; set; }

        [System.ComponentModel.DisplayName("Vrsta pregleda")]
        public Nullable<int> vrstaPregledaID { get; set; }

        [System.ComponentModel.DisplayName("Doktor")]
        public Nullable<int> doktorID { get; set; }
    
        public virtual tblDoktor tblDoktor { get; set; }
        public virtual tblPacijent tblPacijent { get; set; }
        public virtual tblUstanova tblUstanova { get; set; }
        public virtual tblVrstaPregleda tblVrstaPregleda { get; set; }
    }
}
