//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPodtipPregleda
    {

        public int podtipPregledaID { get; set; }

        [System.ComponentModel.DisplayName("Podtip pregleda")]
        public string nazivPodtipaPregleda { get; set; }
        public Nullable<int> tipPregledaID { get; set; }
    
        public virtual tblTipPregleda tblTipPregleda { get; set; }
    }
}
