//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblTipPregleda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTipPregleda()
        {
            this.tblPodtipPregledas = new HashSet<tblPodtipPregleda>();
        }

        public int tipPregledaID { get; set; }

        [System.ComponentModel.DisplayName("Tip pregleda")]
        public string nazivTipaPregleda { get; set; }
        public Nullable<int> vrstaPregledaID { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPodtipPregleda> tblPodtipPregledas { get; set; }
        public virtual tblVrstaPregleda tblVrstaPregleda { get; set; }
    }
}