//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblUstanova
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUstanova()
        {
            this.tblPregleds = new HashSet<tblPregled>();
        }

        public int ustanovaID { get; set; }
        [System.ComponentModel.DisplayName("Naziv ")]
        public string nazivUstanove { get; set; }

        [System.ComponentModel.DisplayName("Adresa")]
        public string adresaUstanove { get; set; }

        [System.ComponentModel.DisplayName("Mesto")]
        public string mestoUstanove { get; set; }


        [System.ComponentModel.DisplayName("Ustanova")]
        public string ustanova
        {
            get
            {
                return nazivUstanove + "," + mestoUstanove;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPregled> tblPregleds { get; set; }
    }
}