//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoktor
    {
        public int doktorID { get; set; }
        public string imeDoktora { get; set; }
        public string prezimeDoktora { get; set; }
        public Nullable<System.DateTime> datumRodjenjaDoktora { get; set; }
        public string brojTelefonaDoktora { get; set; }
        public string brojLicence { get; set; }
        public string specijalizacija { get; set; }
    }
}
