//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCZakazivanjePregleda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUstanova
    {
        public int ustanovaID { get; set; }
        public string nazivUstanove { get; set; }
        public string adresaUstanove { get; set; }
        public string mestoUstanove { get; set; }
    }
}
